version: '3.8'
services:
  webapp:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ${APP_NAME}
    image: "alikberova/cicdtest:latest"
    environment:
      - APP_NAME=CiCdTest
