name: .NET Deployment

on:
  push:
    branches: [ "master", "cicd", "compose"  ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    env:
      app_name: CiCdTest
      tags: alikberova/cicdtest:latest 

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Compose services
      run: |
        docker compose build
        docker compose push

    - name: Create env file
      run: |
        echo "${{ secrets.API_ENV_FILE }}" > .env

    - name: Copy file to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: docker-compose.yml,.env
        target: /usr/cicdtest

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /usr/cicdtest
          docker compose pull
          docker compose down || true
          docker compose --env-file .env up