# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Deployment

on:
  push:
    branches: [ "master", "cicd" ]
  pull_request:
    branches: [ "master", "cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Console App
      run: |
        # Add commands to build your console app, for example:
        dotnet publish -c Release -o build

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: ECHO
      run: echo ${{ secrets.TEST }}

    - name: Copy files to Hetzner Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "build/*"
        target: "/var/myapp"
        strip_components: 1
