name: .NET Deployment

on:
  push:
    branches: [ "master", "cicd", "test" ]

jobs:
  deploy:

    runs-on: windows-latest
    env:
      app_name: CiCdTest
      tags: alikberova/cicdtest:latest 
      project-name: cicdtest
      publish-name: cicdtest-pub

    steps:
    - uses: actions/checkout@v4

    # Optionally, restore and test your project here
    - name: Set up .NET Core
      uses: microsoft/setup-msbuild@v2
      with: 
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: nuget restore
    
    - name: Build and Publish Application to folder
      run: |
         msbuild ${{ env.project-name }} /t:publish /p:Configuration=Release /p:RuntimeIdentifier=win-x64 /p:PublishReadyToRun=True /p:SelfContained=true /p:PublishSingleFile=true /p:RestorePackages=false

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.tags }}
        build-args: |
          APP_NAME=${{ env.app_name }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ env.tags }}
          docker stop testappcontainer || true
          docker rm testappcontainer || true
          docker run -d --name testappcontainer ${{ env.tags }}