name: .NET Deployment

on:
  push:
    branches: [ "master", "cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      app_name: CiCdTest
      tags: alikberova/cicdtest:latest 

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Optionally, restore and test your project here

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.tags }}
        build-args: |
          APP_NAME=${{ env.app_name }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER_NAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull ${{ env.tags }}
          docker stop testappcontainer || true
          docker rm testappcontainer || true
          docker run -d --name testappcontainer ${{ env.tags }}