# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Deployment

on:
  push:
    branches: [ "master", "cicd" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      host: ${{ secrets.HOST }}
      username: ${{ secrets.USER_NAME }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Ping Server
      run: ping -c 4 5.161.114.219

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Console App
      run: |
        # Add commands to build your console app, for example:
        dotnet publish -c Release -o build

    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Copy files to Hetzner Server
      uses: appleboy/scp-action@v0.1.7 #appleboy/scp-action@master
      with:
        host: ${{ env.host }}
        username: ${{ env.username }}
        key: ${{ env.ssh_private_key }}
        port: 22
        source: "build/*"
        target: "/var/myapp"
        strip_components: 1
        debug: true
